# Generated by Django 5.0.4 on 2024-05-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body_post_created_on_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtile',
            new_name='subtitle',
        ),
    ]
